apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r5l95j5ff-python
  janus-idp.io/tekton: r5l95j5ff-python
  backstage.io/kubernetes-id: r5l95j5ff-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r5l95j5ff-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
